version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli==1.18.0 aws-sam-cli==1.12.0 --skip-lock
      - export BUCKET=medupdates-backend-dev
      - npm install
      - npm run genapi
      - sam build
      - pipenv run sam package --template-file .aws-sam/build/template.yaml --s3-bucket $BUCKET --output-template-file deploy.yaml
artifacts:
  files:
    - '**/*'